2021-01-12 14:57:08,540 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-12 15:11:25,279 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-12 15:12:41,117 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\fccDjangoAdmin\__init__.py changed, reloading.
2021-01-12 15:12:42,845 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-12 15:12:51,664 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-12 15:14:57,316 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-12 15:39:00,948 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\fccDjangoAdmin\urls.py changed, reloading.
2021-01-12 15:39:02,840 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-12 15:39:36,846 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\models.py changed, reloading.
2021-01-12 15:39:38,484 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-12 15:47:34,757 django.request 230 WARNING  Not Found: /
2021-01-12 15:50:52,351 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\admin.py changed, reloading.
2021-01-12 15:50:54,468 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-12 15:50:57,621 django.request 230 WARNING  Not Found: /
2021-01-12 15:50:57,657 django.request 230 WARNING  Not Found: /
2021-01-12 15:55:48,632 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\admin.py changed, reloading.
2021-01-12 15:55:50,624 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-12 16:03:11,738 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-12 16:03:33,470 django.request 230 WARNING  Not Found: /favicon.ico
2021-01-12 16:03:34,190 django.request 230 WARNING  Not Found: /favicon.ico
2021-01-12 16:05:00,411 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\admin.py changed, reloading.
2021-01-12 16:05:02,193 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-12 16:10:15,485 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-12 16:12:40,574 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\admin.py changed, reloading.
2021-01-12 16:12:42,247 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-12 16:14:27,420 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-12 16:15:58,778 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\admin.py changed, reloading.
2021-01-12 16:16:00,550 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-12 16:16:07,817 interview.admin 95 INFO     interviewer is in user's group for interviewer2
2021-01-12 16:16:07,828 interview.admin 95 INFO     interviewer is in user's group for interviewer2
2021-01-12 16:17:09,698 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\admin.py changed, reloading.
2021-01-12 16:17:11,456 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-12 16:17:15,955 interview.admin 95 INFO     interviewer is in user's group for interviewer2
2021-01-12 16:17:15,966 interview.admin 95 INFO     interviewer is in user's group for interviewer2
2021-01-12 16:17:18,042 interview.admin 95 INFO     interviewer is in user's group for interviewer2
2021-01-12 16:17:18,053 interview.admin 95 INFO     interviewer is in user's group for interviewer2
2021-01-12 16:17:19,241 interview.admin 95 INFO     interviewer is in user's group for interviewer2
2021-01-12 16:17:19,252 interview.admin 95 INFO     interviewer is in user's group for interviewer2
2021-01-12 16:17:20,105 interview.admin 95 INFO     interviewer is in user's group for interviewer2
2021-01-12 16:17:20,116 interview.admin 95 INFO     interviewer is in user's group for interviewer2
2021-01-12 16:18:35,362 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\admin.py changed, reloading.
2021-01-12 16:18:37,037 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-12 16:18:41,182 interview.admin 82 INFO     interviewer is in user's group for interviewer2
2021-01-12 16:18:41,193 interview.admin 82 INFO     interviewer is in user's group for interviewer2
2021-01-12 16:18:43,595 interview.admin 82 INFO     interviewer is in user's group for interviewer2
2021-01-12 16:18:43,605 interview.admin 82 INFO     interviewer is in user's group for interviewer2
2021-01-12 16:18:44,625 interview.admin 82 INFO     interviewer is in user's group for interviewer2
2021-01-12 16:18:44,635 interview.admin 82 INFO     interviewer is in user's group for interviewer2
2021-01-12 16:18:45,234 interview.admin 82 INFO     interviewer is in user's group for interviewer2
2021-01-12 16:18:45,243 interview.admin 82 INFO     interviewer is in user's group for interviewer2
2021-01-12 16:18:45,651 interview.admin 82 INFO     interviewer is in user's group for interviewer2
2021-01-12 16:18:45,660 interview.admin 82 INFO     interviewer is in user's group for interviewer2
2021-01-12 16:18:46,000 interview.admin 82 INFO     interviewer is in user's group for interviewer2
2021-01-12 16:18:46,010 interview.admin 82 INFO     interviewer is in user's group for interviewer2
2021-01-12 16:19:18,912 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-12 16:20:09,108 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\admin.py changed, reloading.
2021-01-12 16:20:10,723 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-12 16:20:19,272 interview.admin 82 INFO     interviewer is in user's group for interviewer2
2021-01-12 16:20:19,281 interview.admin 82 INFO     interviewer is in user's group for interviewer2
2021-01-12 16:22:20,495 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\admin.py changed, reloading.
2021-01-12 16:22:22,490 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-12 16:22:42,660 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\admin.py changed, reloading.
2021-01-12 16:22:45,017 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-12 16:25:02,610 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\admin.py changed, reloading.
2021-01-12 16:25:04,514 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-12 16:26:25,224 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\admin.py changed, reloading.
2021-01-12 16:26:27,312 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-12 16:27:17,667 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\admin.py changed, reloading.
2021-01-12 16:27:19,332 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-12 16:27:47,641 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\admin.py changed, reloading.
2021-01-12 16:27:49,335 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-12 16:29:35,994 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\admin.py changed, reloading.
2021-01-12 16:29:37,759 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-12 16:40:25,414 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\settings\base.py changed, reloading.
2021-01-12 16:40:27,635 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-12 16:40:49,774 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-12 16:40:58,340 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\settings\base.py changed, reloading.
2021-01-12 16:41:01,337 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-12 16:41:51,793 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-12 16:41:54,562 django.request 230 WARNING  Not Found: /
2021-01-12 16:41:54,643 django.request 230 WARNING  Not Found: /
2021-01-12 18:05:02,068 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\admin.py changed, reloading.
2021-01-12 18:05:04,595 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-12 18:08:40,583 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\admin.py changed, reloading.
2021-01-12 18:08:42,461 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-12 18:10:08,172 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\admin.py changed, reloading.
2021-01-12 18:10:10,712 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-12 18:14:44,043 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-12 18:15:38,216 interview.admin 87 INFO     interviewer is in user's group for interviewer1
2021-01-12 18:15:38,224 interview.admin 87 INFO     interviewer is in user's group for interviewer1
2021-01-12 18:21:29,628 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\admin.py changed, reloading.
2021-01-12 18:21:31,637 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-12 18:28:21,682 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\admin.py changed, reloading.
2021-01-12 18:28:23,676 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-12 18:30:48,672 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-13 14:49:49,538 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\admin.py changed, reloading.
2021-01-13 14:49:51,264 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-13 14:53:12,033 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\admin.py changed, reloading.
2021-01-13 14:53:13,947 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-13 15:15:26,493 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\settings\base.py changed, reloading.
2021-01-13 15:15:28,119 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-13 16:22:58,570 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\admin.py changed, reloading.
2021-01-13 16:23:00,372 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-13 16:23:30,419 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\admin.py changed, reloading.
2021-01-13 16:23:31,970 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-13 16:23:58,876 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\admin.py changed, reloading.
2021-01-13 16:24:00,548 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-13 16:25:35,806 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\admin.py changed, reloading.
2021-01-13 16:25:37,353 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-13 16:39:48,646 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\admin.py changed, reloading.
2021-01-13 16:39:50,908 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-13 16:40:01,323 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-13 16:47:53,750 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\settings\base.py changed, reloading.
2021-01-13 16:47:55,841 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-13 16:48:06,925 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\settings\base.py changed, reloading.
2021-01-13 16:48:08,890 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-13 17:03:16,601 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\models.py changed, reloading.
2021-01-13 17:03:18,519 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-13 17:04:08,148 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\admin.py changed, reloading.
2021-01-13 17:04:10,070 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-13 17:06:57,674 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\candidate_fields.py changed, reloading.
2021-01-13 17:06:59,658 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-13 17:07:07,399 django.request 230 ERROR    Internal Server Error: /admin/interview/candidate/5/change/
Traceback (most recent call last):
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\contrib\admin\options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\contrib\admin\sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\contrib\admin\options.py", line 1656, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\contrib\admin\options.py", line 1534, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\contrib\admin\options.py", line 1569, in _changeform_view
    request, obj, change=not add, fields=flatten_fieldsets(fieldsets)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\contrib\admin\utils.py", line 97, in flatten_fieldsets
    for name, opts in fieldsets:
ValueError: too many values to unpack (expected 2)
2021-01-13 17:08:04,312 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\candidate_fields.py changed, reloading.
2021-01-13 17:08:06,341 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-13 17:08:50,931 django.request 230 WARNING  Not Found: /Ñî±ó-²âÊÔ¹¤³ÌÊ¦¼òÀú.doc
2021-01-13 17:09:41,487 django.request 230 WARNING  Not Found: /Ñî±ó-²âÊÔ¹¤³ÌÊ¦¼òÀú.doc
2021-01-13 17:16:45,113 django.request 230 WARNING  Not Found: /Ñî±ó-²âÊÔ¹¤³ÌÊ¦¼òÀú.doc
2021-01-13 17:23:07,107 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\settings\base.py changed, reloading.
2021-01-13 17:23:09,071 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-13 17:23:49,880 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\models.py changed, reloading.
2021-01-13 17:23:51,766 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-13 17:24:04,606 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\models.py changed, reloading.
2021-01-13 17:24:06,655 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-13 17:26:49,111 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\models.py changed, reloading.
2021-01-13 17:26:51,148 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-13 17:27:56,505 django.request 230 ERROR    Internal Server Error: /admin/interview/candidate/5/change/
Traceback (most recent call last):
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\contrib\admin\options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\contrib\admin\sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\contrib\admin\options.py", line 1656, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\contrib\admin\options.py", line 1534, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\contrib\admin\options.py", line 1580, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\contrib\admin\options.py", line 1093, in save_model
    obj.save()
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\db\models\base.py", line 754, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\db\models\base.py", line 792, in save_base
    force_update, using, update_fields,
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\db\models\base.py", line 870, in _save_table
    for f in non_pks]
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\db\models\base.py", line 870, in <listcomp>
    for f in non_pks]
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\db\models\fields\files.py", line 307, in pre_save
    file.save(file.name, file.file, save=False)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\db\models\fields\files.py", line 86, in save
    name = self.field.generate_filename(self.instance, name)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\db\models\fields\files.py", line 322, in generate_filename
    filename = self.upload_to(instance, filename)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\models.py", line 20, in upload_to
    return '/'.join([settings.MEDIA_ROOT, instance.user_name, filename])
AttributeError: 'Candidate' object has no attribute 'user_name'
2021-01-13 17:28:37,281 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\models.py changed, reloading.
2021-01-13 17:28:39,423 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-13 17:29:00,770 django.request 230 WARNING  Not Found: /upload/C:/Users/86181/Desktop/myword/ÄûÃÊ°à¿Î³Ì/fccDjangoAdmin/upload/ÀîÐ¡Áú/Ñî±ó-²âÊÔ¹¤³ÌÊ¦¼òÀú_ÐÂ.doc
2021-01-13 17:35:05,940 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\admin.py changed, reloading.
2021-01-13 17:35:08,040 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-13 17:36:40,726 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\admin.py changed, reloading.
2021-01-13 17:36:42,566 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-13 17:38:39,993 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\admin.py changed, reloading.
2021-01-13 17:38:42,012 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-13 17:49:11,889 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\fccDjangoAdmin\urls.py changed, reloading.
2021-01-13 17:49:14,135 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-13 17:49:52,403 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\admin.py changed, reloading.
2021-01-13 17:49:54,713 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-13 17:50:11,147 django.request 230 ERROR    Internal Server Error: /resume/5/
Traceback (most recent call last):
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\views.py", line 12, in read_resume
    load_html = PyDocX.to_html(file_path)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\pydocx\pydocx.py", line 13, in to_html
    return PyDocXHTMLExporter(path_or_stream).export()
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\pydocx\export\html.py", line 211, in export
    for result in super(PyDocXHTMLExporter, self).export()
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\pydocx\export\html.py", line 209, in <genexpr>
    result.to_html() if isinstance(result, HtmlTag)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\pydocx\export\base.py", line 110, in export
    document = self.main_document_part.document
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\pydocx\openxml\packaging\main_document_part.py", line 49, in document
    self._document = self.load_document()
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\pydocx\openxml\packaging\main_document_part.py", line 53, in load_document
    self._document = Document.load(self.root_element, container=self)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\pydocx\models.py", line 280, in load
    other=element.tag,
pydocx.models.XmlRootElementMismatchException: Expected root element document but got themeManager instead
2021-01-13 17:52:13,951 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-13 17:52:25,140 django.request 230 ERROR    Internal Server Error: /admin/interview/candidate/
Traceback (most recent call last):
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\db\models\options.py", line 575, in get_field
    return self.fields_map[field_name]
KeyError: 'get_resume'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\contrib\admin\utils.py", line 265, in lookup_field
    f = _get_non_gfk_field(opts, name)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\contrib\admin\utils.py", line 296, in _get_non_gfk_field
    field = opts.get_field(name)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\db\models\options.py", line 577, in get_field
    raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
django.core.exceptions.FieldDoesNotExist: Candidate has no field named 'get_resume'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\contrib\admin\templatetags\base.py", line 33, in render
    return super().render(context)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\template\library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 341, in result_list
    'results': list(results(cl)),
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 314, in results
    yield ResultList(form, items_for_result(cl, res, form))
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 308, in __init__
    super().__init__(*items)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 233, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\contrib\admin\utils.py", line 274, in lookup_field
    value = attr(obj)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\admin.py", line 117, in get_resume
    return mark_safe(u'<a href="/resume/%s" target="_blank">%s</a' % (obj.id, obj.resume.split('/')[-1]))
AttributeError: 'FieldFile' object has no attribute 'split'
2021-01-13 17:52:56,933 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-13 17:53:06,332 django.request 230 ERROR    Internal Server Error: /resume/5/
Traceback (most recent call last):
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\views.py", line 12, in read_resume
    load_html = PyDocX.to_html(file_path)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\pydocx\pydocx.py", line 13, in to_html
    return PyDocXHTMLExporter(path_or_stream).export()
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\pydocx\export\html.py", line 211, in export
    for result in super(PyDocXHTMLExporter, self).export()
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\pydocx\export\html.py", line 209, in <genexpr>
    result.to_html() if isinstance(result, HtmlTag)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\pydocx\export\base.py", line 110, in export
    document = self.main_document_part.document
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\pydocx\openxml\packaging\main_document_part.py", line 49, in document
    self._document = self.load_document()
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\pydocx\openxml\packaging\main_document_part.py", line 53, in load_document
    self._document = Document.load(self.root_element, container=self)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\pydocx\models.py", line 280, in load
    other=element.tag,
pydocx.models.XmlRootElementMismatchException: Expected root element document but got themeManager instead
2021-01-13 18:01:27,770 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-13 18:01:28,570 django.request 230 ERROR    Internal Server Error: /resume/5/
Traceback (most recent call last):
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\views.py", line 12, in read_resume
    load_html = PyDocX.to_html(file_path)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\pydocx\pydocx.py", line 13, in to_html
    return PyDocXHTMLExporter(path_or_stream).export()
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\pydocx\export\html.py", line 211, in export
    for result in super(PyDocXHTMLExporter, self).export()
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\pydocx\export\html.py", line 209, in <genexpr>
    result.to_html() if isinstance(result, HtmlTag)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\pydocx\export\base.py", line 110, in export
    document = self.main_document_part.document
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\pydocx\openxml\packaging\main_document_part.py", line 49, in document
    self._document = self.load_document()
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\pydocx\openxml\packaging\main_document_part.py", line 53, in load_document
    self._document = Document.load(self.root_element, container=self)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\pydocx\models.py", line 280, in load
    other=element.tag,
pydocx.models.XmlRootElementMismatchException: Expected root element document but got themeManager instead
2021-01-13 18:02:26,872 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\views.py changed, reloading.
2021-01-13 18:02:28,885 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-13 18:02:38,247 django.request 230 ERROR    Internal Server Error: /resume/5/
Traceback (most recent call last):
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\views.py", line 12, in read_resume
    load_html = PyDocX.to_html(file_path)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\pydocx\pydocx.py", line 13, in to_html
    return PyDocXHTMLExporter(path_or_stream).export()
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\pydocx\export\html.py", line 211, in export
    for result in super(PyDocXHTMLExporter, self).export()
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\pydocx\export\html.py", line 209, in <genexpr>
    result.to_html() if isinstance(result, HtmlTag)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\pydocx\export\base.py", line 110, in export
    document = self.main_document_part.document
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\pydocx\openxml\packaging\main_document_part.py", line 49, in document
    self._document = self.load_document()
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\pydocx\openxml\packaging\main_document_part.py", line 53, in load_document
    self._document = Document.load(self.root_element, container=self)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\pydocx\models.py", line 280, in load
    other=element.tag,
pydocx.models.XmlRootElementMismatchException: Expected root element document but got themeManager instead
2021-01-13 18:04:32,514 django.request 230 ERROR    Internal Server Error: /resume/5/
Traceback (most recent call last):
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\views.py", line 12, in read_resume
    load_html = PyDocX.to_html(file_path)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\pydocx\pydocx.py", line 13, in to_html
    return PyDocXHTMLExporter(path_or_stream).export()
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\pydocx\export\html.py", line 211, in export
    for result in super(PyDocXHTMLExporter, self).export()
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\pydocx\export\html.py", line 209, in <genexpr>
    result.to_html() if isinstance(result, HtmlTag)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\pydocx\export\base.py", line 110, in export
    document = self.main_document_part.document
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\pydocx\openxml\packaging\main_document_part.py", line 49, in document
    self._document = self.load_document()
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\pydocx\openxml\packaging\main_document_part.py", line 53, in load_document
    self._document = Document.load(self.root_element, container=self)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\pydocx\models.py", line 280, in load
    other=element.tag,
pydocx.models.XmlRootElementMismatchException: Expected root element document but got themeManager instead
2021-01-13 18:18:33,094 django.request 230 ERROR    Internal Server Error: /resume/4/
Traceback (most recent call last):
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\views.py", line 12, in read_resume
    load_html = PyDocX.to_html(file_path)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\pydocx\pydocx.py", line 13, in to_html
    return PyDocXHTMLExporter(path_or_stream).export()
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\pydocx\export\html.py", line 211, in export
    for result in super(PyDocXHTMLExporter, self).export()
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\pydocx\export\html.py", line 209, in <genexpr>
    result.to_html() if isinstance(result, HtmlTag)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\pydocx\export\base.py", line 109, in export
    raise MalformedDocxException
pydocx.exceptions.MalformedDocxException
2021-01-13 18:24:42,159 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\views.py changed, reloading.
2021-01-13 18:24:44,200 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-13 18:25:32,995 django.request 230 ERROR    Internal Server Error: /resume/5/
Traceback (most recent call last):
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\views.py", line 36, in read_resume
    response['Content-Disposition'] = f"attachment; filename*=UTF-8''{escape_uri_path(instance.name)}"
AttributeError: 'Candidate' object has no attribute 'name'
2021-01-13 18:26:18,677 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\views.py changed, reloading.
2021-01-13 18:26:20,646 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-13 18:28:07,530 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\views.py changed, reloading.
2021-01-13 18:28:09,506 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-13 18:30:21,501 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\views.py changed, reloading.
2021-01-13 18:30:23,622 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-13 18:34:43,423 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-13 18:37:12,809 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\views.py changed, reloading.
2021-01-13 18:37:14,820 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-13 18:38:25,744 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\views.py changed, reloading.
2021-01-13 18:38:28,012 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-13 18:39:50,939 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\views.py changed, reloading.
2021-01-13 18:39:53,051 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-13 19:42:37,884 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\views.py changed, reloading.
2021-01-13 19:42:41,226 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-13 19:43:44,482 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\views.py changed, reloading.
2021-01-13 19:43:46,402 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-13 19:46:53,872 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\views.py changed, reloading.
2021-01-13 19:46:56,412 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-13 19:49:32,406 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\admin.py changed, reloading.
2021-01-13 19:49:34,432 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-13 19:52:46,020 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\admin.py changed, reloading.
2021-01-13 19:52:48,251 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-13 19:54:43,391 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\admin.py changed, reloading.
2021-01-13 19:54:45,480 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-13 20:05:59,087 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\admin.py changed, reloading.
2021-01-13 20:06:01,202 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-13 20:06:05,141 django.request 230 ERROR    Internal Server Error: /admin/interview/candidate/
Traceback (most recent call last):
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\db\models\options.py", line 575, in get_field
    return self.fields_map[field_name]
KeyError: 'upload_resume'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\contrib\admin\utils.py", line 265, in lookup_field
    f = _get_non_gfk_field(opts, name)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\contrib\admin\utils.py", line 296, in _get_non_gfk_field
    field = opts.get_field(name)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\db\models\options.py", line 577, in get_field
    raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
django.core.exceptions.FieldDoesNotExist: Candidate has no field named 'upload_resume'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\contrib\admin\templatetags\base.py", line 33, in render
    return super().render(context)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\template\library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 341, in result_list
    'results': list(results(cl)),
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 314, in results
    yield ResultList(form, items_for_result(cl, res, form))
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 308, in __init__
    super().__init__(*items)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 233, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\contrib\admin\utils.py", line 274, in lookup_field
    value = attr(obj)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\admin.py", line 121, in upload_resume
    u'type="file" name="resume">%s<input type="submit"></form>' % (obj.id))
TypeError: not enough arguments for format string
2021-01-13 20:06:43,355 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\admin.py changed, reloading.
2021-01-13 20:06:45,496 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-13 20:08:02,868 django.security.csrf 230 WARNING  Forbidden (CSRF token missing or incorrect.): /admin/interview/candidate/upload/resume/4/
2021-01-13 20:08:25,046 django.security.csrf 230 WARNING  Forbidden (CSRF token missing or incorrect.): /admin/interview/candidate/upload/resume/4/
2021-01-13 20:08:42,951 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\admin.py changed, reloading.
2021-01-13 20:08:45,006 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-13 20:30:24,777 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\admin.py changed, reloading.
2021-01-13 20:30:26,884 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-13 20:41:47,363 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-13 20:57:00,924 django.request 230 WARNING  Not Found: /favicon.ico
2021-01-13 20:57:23,685 django.request 230 ERROR    Internal Server Error: /resume/add/
Traceback (most recent call last):
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1774, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'add'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\views.py", line 27, in read_resume
    instance = Candidate.objects.get(pk=pk)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\db\models\query.py", line 418, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\db\models\query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\db\models\query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\db\models\query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\db\models\sql\query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\db\models\sql\query.py", line 1380, in _add_q
    split_subq=split_subq, check_filterable=check_filterable,
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\db\models\sql\query.py", line 1319, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\db\models\sql\query.py", line 1165, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\db\models\lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\db\models\lookups.py", line 76, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1778, in get_prep_value
    ) from e
ValueError: Field 'id' expected a number but got 'add'.
2021-01-13 21:00:23,407 django.request 230 WARNING  Not Found: /favicon.ico
2021-01-14 14:48:34,679 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\settings\base.py changed, reloading.
2021-01-14 14:48:37,531 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-14 14:50:36,275 interview.performance 13 INFO     0.3169984817504883 /admin/ {}
2021-01-14 14:50:36,816 interview.performance 13 INFO     0.13499855995178223 /admin/jobs/job/ {}
2021-01-14 14:50:36,909 interview.performance 13 INFO     0.037000417709350586 /admin/jsi18n/ {}
2021-01-14 14:51:05,246 interview.performance 13 INFO     0.4510018825531006 /admin/interview/candidate/ {}
2021-01-14 14:51:05,364 interview.performance 13 INFO     0.02899932861328125 /admin/jsi18n/ {}
2021-01-14 14:51:13,197 interview.performance 13 INFO     0.08099961280822754 /admin/ {}
2021-01-14 14:51:14,005 interview.performance 13 INFO     0.5180001258850098 /admin/interview/candidate/ {}
2021-01-14 14:51:14,136 interview.performance 13 INFO     0.038001298904418945 /admin/jsi18n/ {}
2021-01-15 14:29:14,099 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\settings\base.py changed, reloading.
2021-01-15 14:31:13,550 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-15 14:35:39,488 interview.performance 13 INFO     0.10499954223632812 / {}
2021-01-15 14:35:39,488 django.request 230 WARNING  Not Found: /
2021-01-15 14:35:39,503 interview.performance 13 INFO     0.008999347686767578 / {}
2021-01-15 14:35:39,504 django.request 230 WARNING  Not Found: /
2021-01-15 14:53:53,240 interview.performance 13 INFO     1.8989970684051514 /admin/ {}
2021-01-15 14:53:54,204 interview.performance 13 INFO     1.1540014743804932 /admin/interview/candidate/5/change/ {}
2021-01-15 14:53:54,270 interview.performance 13 INFO     0.7780005931854248 /admin/interview/candidate/ {}
2021-01-15 14:53:54,336 interview.performance 13 INFO     0.03099966049194336 /admin/jsi18n/ {}
2021-01-15 15:26:50,256 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\performance.py changed, reloading.
2021-01-15 15:26:52,587 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-15 15:29:01,212 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\performance.py changed, reloading.
2021-01-15 15:29:03,365 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-15 15:34:31,852 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\performance.py changed, reloading.
2021-01-15 15:34:34,373 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-15 15:36:14,677 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\performance.py changed, reloading.
2021-01-15 15:36:16,847 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-15 15:36:46,967 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\performance.py changed, reloading.
2021-01-15 15:36:49,302 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-15 15:45:51,176 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-15 15:46:15,465 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\settings\base.py changed, reloading.
2021-01-15 15:46:18,034 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-15 15:47:26,511 interview.performance 35 INFO     0.43900108337402344 /admin/ {}
2021-01-15 15:47:27,478 interview.performance 35 INFO     0.6549985408782959 /admin/interview/candidate/ {}
2021-01-15 15:47:27,547 interview.performance 35 INFO     0.03999948501586914 /admin/jsi18n/ {}
2021-01-15 15:47:30,801 interview.performance 35 INFO     0.468001127243042 /admin/interview/candidate/2/change/ {}
2021-01-15 15:47:30,869 interview.performance 35 INFO     0.028998374938964844 /admin/jsi18n/ {}
2021-01-15 15:47:37,118 interview.performance 35 INFO     0.24199771881103516 /admin/jobs/job/ {}
2021-01-15 15:47:37,179 interview.performance 35 INFO     0.035996437072753906 /admin/jsi18n/ {}
2021-01-15 15:47:58,919 interview.performance 35 INFO     1.913011074066162 /admin/ {}
2021-01-15 15:48:01,972 interview.performance 35 INFO     0.5329976081848145 /admin/interview/candidate/ {}
2021-01-15 15:48:02,017 interview.performance 35 INFO     0.021999835968017578 /admin/jsi18n/ {}
2021-01-18 10:24:11,981 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-18 10:24:37,422 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-18 10:25:36,025 interview.performance 35 INFO     0.005001544952392578 /admin {}
2021-01-18 10:25:36,607 django.security.SuspiciousSession 131 WARNING  Session data corrupted
2021-01-18 10:25:36,647 interview.performance 35 INFO     0.6129992008209229 /admin/ {}
2021-01-18 10:25:36,672 django.security.SuspiciousSession 131 WARNING  Session data corrupted
2021-01-18 10:25:36,674 django.security.SuspiciousSession 131 WARNING  Session data corrupted
2021-01-18 10:25:36,677 interview.performance 35 INFO     0.021999120712280273 /admin/ {}
2021-01-18 10:25:36,714 interview.performance 35 INFO     0.054015159606933594 /admin/login/ {'next': '/admin/'}
2021-01-18 10:25:36,739 django.security.SuspiciousSession 131 WARNING  Session data corrupted
2021-01-18 10:25:36,770 interview.performance 35 INFO     0.04900169372558594 /admin/login/ {'next': '/admin/'}
2021-01-18 10:25:37,184 interview.performance 35 INFO     0.07599687576293945 /favicon.ico {}
2021-01-18 10:25:37,185 django.request 230 WARNING  Not Found: /favicon.ico
2021-01-18 10:25:37,202 django.security.SuspiciousSession 131 WARNING  Session data corrupted
2021-01-18 10:25:38,529 django.security.SuspiciousSession 131 WARNING  Session data corrupted
2021-01-18 10:25:44,989 interview.performance 35 INFO     6.4800026416778564 /admin/login/ {'next': '/admin/'}
2021-01-18 10:25:45,773 interview.performance 35 INFO     0.7739872932434082 /admin/ {}
2021-01-18 11:43:36,024 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\admin.py changed, reloading.
2021-01-18 11:43:38,241 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-20 16:14:28,781 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\settings\local.py changed, reloading.
2021-01-20 16:14:31,558 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-20 16:15:20,025 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\fccDjangoAdmin\__init__.py changed, reloading.
2021-01-20 16:15:22,464 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-20 16:16:44,292 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\admin.py changed, reloading.
2021-01-20 16:16:46,623 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-20 16:19:44,444 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\fccDjangoAdmin\__init__.py changed, reloading.
2021-01-20 16:19:46,817 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-20 16:21:13,006 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\venv\Lib\site-packages\tornado\tcpserver.py changed, reloading.
2021-01-20 16:21:16,165 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-20 16:23:13,989 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\settings\local.py changed, reloading.
2021-01-20 16:23:16,391 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-20 16:31:45,687 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\fccDjangoAdmin\celery.py changed, reloading.
2021-01-20 16:31:48,813 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-20 16:33:51,665 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-20 16:33:53,569 interview.performance 35 INFO     0.06200051307678223 / {}
2021-01-20 16:33:53,570 django.request 230 WARNING  Not Found: /
2021-01-20 16:33:53,815 interview.performance 35 INFO     0.00999903678894043 / {}
2021-01-20 16:33:53,817 django.request 230 WARNING  Not Found: /
2021-01-20 16:34:01,383 interview.performance 35 INFO     0.7719993591308594 /admin/ {}
2021-01-20 16:34:02,364 interview.performance 35 INFO     0.5369975566864014 /admin/ {}
2021-01-20 16:34:05,431 interview.performance 35 INFO     0.8140006065368652 /admin/interview/candidate/ {}
2021-01-20 16:34:05,596 interview.performance 35 INFO     0.06499862670898438 /admin/jsi18n/ {}
2021-01-20 16:34:09,840 interview.performance 35 INFO     0.27899742126464844 /admin/interview/candidate/ {}
2021-01-20 16:34:10,402 interview.performance 35 INFO     0.545001745223999 /admin/interview/candidate/ {}
2021-01-20 16:34:10,481 interview.performance 35 INFO     0.029999732971191406 /admin/jsi18n/ {}
2021-01-20 16:40:00,333 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\fccDjangoAdmin\celery.py changed, reloading.
2021-01-20 16:40:02,836 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-20 17:00:27,320 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\fccDjangoAdmin\celery.py changed, reloading.
2021-01-20 17:00:30,863 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-20 17:03:58,243 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\fccDjangoAdmin\celery.py changed, reloading.
2021-01-20 17:04:00,709 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-20 17:05:12,547 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-20 17:06:11,144 interview.performance 35 INFO     0.26399922370910645 /admin/interview/candidate/ {}
2021-01-20 17:06:11,729 interview.performance 35 INFO     0.5420000553131104 /admin/interview/candidate/ {}
2021-01-20 17:06:11,829 interview.performance 35 INFO     0.04099774360656738 /admin/jsi18n/ {}
2021-01-20 17:09:47,407 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-20 17:09:56,411 interview.performance 35 INFO     0.375 /admin/ {}
2021-01-20 17:09:57,049 interview.performance 35 INFO     0.4760003089904785 /admin/interview/candidate/ {}
2021-01-20 17:09:57,101 interview.performance 35 INFO     0.024000883102416992 /admin/jsi18n/ {}
2021-01-20 17:10:00,671 interview.performance 35 INFO     0.20699667930603027 /admin/interview/candidate/ {}
2021-01-20 17:10:01,209 interview.performance 35 INFO     0.5200014114379883 /admin/interview/candidate/ {}
2021-01-20 17:10:01,318 interview.performance 35 INFO     0.055999755859375 /admin/jsi18n/ {}
2021-01-20 17:11:54,865 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\admin.py changed, reloading.
2021-01-20 17:11:57,411 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-01-20 17:19:58,949 interview.performance 35 INFO     0.33699846267700195 /admin/ {}
2021-01-20 17:19:59,715 interview.performance 35 INFO     0.548999547958374 /admin/interview/candidate/ {}
2021-01-20 17:19:59,772 interview.performance 35 INFO     0.024999380111694336 /admin/jsi18n/ {}
2021-01-20 17:20:05,365 interview.performance 35 INFO     0.20299649238586426 /admin/interview/candidate/ {}
2021-01-20 17:20:05,817 interview.performance 35 INFO     0.43900060653686523 /admin/interview/candidate/ {}
2021-01-20 17:20:05,878 interview.performance 35 INFO     0.020000219345092773 /admin/jsi18n/ {}
2021-01-21 18:05:43,347 interview.performance 35 INFO     0.24499940872192383 /admin/ {}
2021-01-21 18:05:44,028 interview.performance 35 INFO     0.4659996032714844 /admin/interview/candidate/ {}
2021-01-21 18:05:44,086 interview.performance 35 INFO     0.017998218536376953 /admin/jsi18n/ {}
2021-01-26 15:22:24,343 interview.performance 35 INFO     0.3900001049041748 /admin/ {}
2021-01-26 15:22:24,518 interview.performance 35 INFO     0.14400172233581543 /admin/ {}
2021-01-26 15:22:26,569 interview.performance 35 INFO     0.5370004177093506 /admin/interview/candidate/ {}
2021-01-26 15:22:26,655 interview.performance 35 INFO     0.03200054168701172 /admin/jsi18n/ {}
2021-01-26 15:22:28,751 interview.performance 35 INFO     0.49399805068969727 /admin/interview/candidate/5/change/ {}
2021-01-26 15:22:28,814 interview.performance 35 INFO     0.02700018882751465 /admin/jsi18n/ {}
2021-02-01 15:03:19,380 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\tasks.py changed, reloading.
2021-02-01 15:03:24,207 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-02-01 15:03:48,149 django.utils.autoreload 240 INFO     C:\Users\86181\Desktop\myword\ÄûÃÊ°à¿Î³Ì\fccDjangoAdmin\interview\tasks.py changed, reloading.
2021-02-01 15:03:50,682 django.utils.autoreload 617 INFO     Watching for file changes with StatReloader
2021-02-01 16:56:35,180 interview.performance 35 INFO     0.259998083114624 /admin/ {}
2021-02-01 16:56:35,508 interview.performance 35 INFO     0.08399772644042969 /admin/ {}
2021-02-01 16:56:41,566 interview.performance 35 INFO     0.5199999809265137 /admin/interview/candidate/ {}
2021-02-01 16:56:41,627 interview.performance 35 INFO     0.029997587203979492 /admin/jsi18n/ {}
2021-02-01 16:56:45,401 interview.performance 35 INFO     0.13701391220092773 /admin/jobs/job/ {}
2021-02-01 16:56:45,443 interview.performance 35 INFO     0.02101874351501465 /admin/jsi18n/ {}
